# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updatetd',
            new_name='updated',
        ),
    ]
